### PR TITLE
Support Forward Proxy Authentication

### PR DESCRIPTION
**Pull request by frenche**
Along with some other commits.

Cheers,
Isaac B.

### CODE REVIEW

**Comment by simo5** [comment]
Btw, thanks a lot for the patches, they are going in the right direction, mostly :)

**Comment by frenche** [comment]
Thanks a lot!

**Comment by frenche** [comment]
Hi Simo,

I updated the commits based on your suggestions (sorry for the little git mess).

Hope I didn't take the 'init_cfg' too far :)

Regards,
Isaac B.

**Comment by simo5** [comment]
I correct a few typos, and changed the condition of the first patch as mc != NULL is necessary but not sufficient for NTLM, you need cfg->gss_conn_ctx to have a successful NTLM auth for now.
I pushed all to master except the last one as I'd like to see python-gssapi+python-requests used instead of curl. Please opena  new pull request for the SPNEGO test.

**Pull request closed without merging**
