### PR TITLE
Add docs for new GssapiDelegCcachePerms option

### PR DESCRIPTION
**Pull request by simo5**
Signed-off-by: Simo Sorce <simo@redhat.com>

### CODE REVIEW

**Comment by simo5** [comment]
@frenche please check if this is ok

**Comment by frenche** [comment]
Please merge, the doc is clear.
I'm not sure I understand how the uid case works though as apache child are unprivileged, but I did't look at the code yet.

**Comment by simo5** [comment]
The uid setting works only if apache is running as root of course.

**Comment by frenche** [comment]
Ok, make sense.

**Pull request closed without merging**
