### PR TITLE
Make NTLM SSP support optional (fixes #52)

### LINKED ISSUE #52: mod_auth_gssapi unconditionally includes gssapi/gssapi_ntlmssp.h
In my installation on Debian 8 there is no gssapi/gssapi_ntlmssp.h, still mod_auth_gssapi tries to include it in mod_auth_gssapi.h line 9.

I tried both v1.2.0 and v1.3.0 - both are affected. HEAD should be affected as well, since there were not related changes.

Error message:
```
/usr/share/apr-1.0/build/libtool --no-silent  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -Iasn1c  -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -DLINUX -D_REENTRANT -D_GNU_SOURCE    -pthread -isystem /usr/include/mit-krb5  -I/usr/include/apache2  -I/usr/include/apr-1.0  -g -O2 -MT mod_auth_gssapi_la-mod_auth_gssapi.lo -MD -MP -MF .deps/mod_auth_gssapi_la-mod_auth_gssapi.Tpo -c -o mod_auth_gssapi_la-mod_auth_gssapi.lo `test -f 'mod_auth_gssapi.c' || echo './'`mod_auth_gssapi.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -Iasn1c -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DLINUX -D_REENTRANT -D_GNU_SOURCE -pthread -isystem /usr/include/mit-krb5 -I/usr/include/apache2 -I/usr/include/apr-1.0 -g -O2 -MT mod_auth_gssapi_la-mod_auth_gssapi.lo -MD -MP -MF .deps/mod_auth_gssapi_la-mod_auth_gssapi.Tpo -c mod_auth_gssapi.c  -fPIC -DPIC -o .libs/mod_auth_gssapi_la-mod_auth_gssapi.o
In file included from mod_auth_gssapi.c:25:0:
mod_auth_gssapi.h:9:35: fatal error: gssapi/gssapi_ntlmssp.h: No such file or directory
 #include <gssapi/gssapi_ntlmssp.h>
                                   ^
compilation terminated.
Makefile:481: recipe for target 'mod_auth_gssapi_la-mod_auth_gssapi.lo' failed
```

Dockerfile to reproduce:
```Dockerfile
FROM debian:8
MAINTAINER ...
ENV DEBIAN_FRONTEND noninteractive

VOLUME /export

RUN apt-get -y update && apt-get -y install build-essential autoconf libtool pkg-config apache2-dev libkrb5-dev libssl-dev

ADD mod_auth_gssapi mod_auth_gssapi

RUN cd mod_auth_gssapi && mkdir m4 && autoreconf -fi && ./configure && make && make DESTDIR=/export install
```

### PR DESCRIPTION
**Pull request by devurandom**

### CODE REVIEW

**Comment by simo5** [comment]
I think all we need really is to change gss_mech_ntlmssp to be of type gss_OID (a pointer) and define it to GSS_C_NO_OID when gssapi/gssapi_ntlmssp.h is not available.

Then change a couple of callers to make sure they do not balk when it is NULL.

**Comment by devurandom** [comment]
Second try. Be warned: I couldn't test it, yet.

**Comment by simo5** [comment]
Ah I did not see you proposed a new fix, so I opened #54 
note that your code fails to compile if you *do* have gssapi_nlmssp.h

Can you test #54 ?
If it works for you I'll add a comment about it being co-authored by you and push that one.

**Comment by devurandom** [comment]
Oups, yeah, I overlooked that config.h is not the first to be included...

**Pull request closed without merging**
