### PR TITLE
Declare mag_complete outside the ifdef block

### PR DESCRIPTION
**Pull request by simo5**
Fix issue reported in #106

### CODE REVIEW

**Comment by simo5** [comment]
@frenche or @frozencemetery can you ack/nack this ?

**Comment by frozencemetery** [comment]
It looks okay to me as well, but I'm surprised we work at all without the cred store extension.

**Comment by frozencemetery** [comment]
Yeah, we don't build there.

```
[root@rhel6inacan mod_auth_gssapi]# autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:1: error: Autoconf version 2.69 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
[root@rhel6inacan mod_auth_gssapi]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.8 (Santiago)
[root@rhel6inacan mod_auth_gssapi]#
```

**Comment by frenche** [comment]
@frozencemetery hmm, this failure seem related to autoconf version, not cred-store related.

**Comment by frozencemetery** [comment]
@frenche the first failure definitely is because we have a newer autoconf dependency.  The second isn't; I grabbed the tarball, which has the buildsystem generated (i.e., after autoconf ran) already.  It's not caused by this commit so it's fine if we want to include the fix, but if we actually want to work on el6 we need to do more than is in this commit.

**Comment by frenche** [comment]
The second failure also doesn't seem related to lack of cred-store support (apache version perhaps?).
There are probably systems out there lacking cred-store support, where we'd still want to build (see issue).

**Comment by frenche** [comment]
Actually, the second failure seem to be due to lack of mod_session (the first error).

**Comment by simo5** [comment]
Please open an issue or a PR for other bugs in configure or dependency checks

**Pull request closed without merging**
