### PR TITLE
Add list of directives

### PR DESCRIPTION
**Pull request by simo5**
This allows to consult the whole list in one place and then jump to the
desired section as needed.
Also fix some minor formatting discrepancies.

### CODE REVIEW

**Comment by simo5** [comment]
@frozencemetery PTAL

**Comment by frozencemetery** [comment]
This looks good.  Do you think we should index the environment variable at the top too?

**Comment by simo5** [comment]
The env var is in a different section so I did not put it there.

**Comment by simo5** [comment]
Maybe we could move the whole session up so it is more visibile? It is unlikely to grow much in size.

**Comment by frozencemetery** [comment]
Yeah, my worry is that it'll get lost now, not that its size particularly warrants an index.

**Comment by simo5** [comment]
Ok moved env vars up and the list of directive inside the Config Directive para

**Pull request closed without merging**
