### PR TITLE
Allow building without NTLMSSP support

### LINKED ISSUE #52: mod_auth_gssapi unconditionally includes gssapi/gssapi_ntlmssp.h
In my installation on Debian 8 there is no gssapi/gssapi_ntlmssp.h, still mod_auth_gssapi tries to include it in mod_auth_gssapi.h line 9.

I tried both v1.2.0 and v1.3.0 - both are affected. HEAD should be affected as well, since there were not related changes.

Error message:
```
/usr/share/apr-1.0/build/libtool --no-silent  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -Iasn1c  -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -DLINUX -D_REENTRANT -D_GNU_SOURCE    -pthread -isystem /usr/include/mit-krb5  -I/usr/include/apache2  -I/usr/include/apr-1.0  -g -O2 -MT mod_auth_gssapi_la-mod_auth_gssapi.lo -MD -MP -MF .deps/mod_auth_gssapi_la-mod_auth_gssapi.Tpo -c -o mod_auth_gssapi_la-mod_auth_gssapi.lo `test -f 'mod_auth_gssapi.c' || echo './'`mod_auth_gssapi.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -Iasn1c -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DLINUX -D_REENTRANT -D_GNU_SOURCE -pthread -isystem /usr/include/mit-krb5 -I/usr/include/apache2 -I/usr/include/apr-1.0 -g -O2 -MT mod_auth_gssapi_la-mod_auth_gssapi.lo -MD -MP -MF .deps/mod_auth_gssapi_la-mod_auth_gssapi.Tpo -c mod_auth_gssapi.c  -fPIC -DPIC -o .libs/mod_auth_gssapi_la-mod_auth_gssapi.o
In file included from mod_auth_gssapi.c:25:0:
mod_auth_gssapi.h:9:35: fatal error: gssapi/gssapi_ntlmssp.h: No such file or directory
 #include <gssapi/gssapi_ntlmssp.h>
                                   ^
compilation terminated.
Makefile:481: recipe for target 'mod_auth_gssapi_la-mod_auth_gssapi.lo' failed
```

Dockerfile to reproduce:
```Dockerfile
FROM debian:8
MAINTAINER ...
ENV DEBIAN_FRONTEND noninteractive

VOLUME /export

RUN apt-get -y update && apt-get -y install build-essential autoconf libtool pkg-config apache2-dev libkrb5-dev libssl-dev

ADD mod_auth_gssapi mod_auth_gssapi

RUN cd mod_auth_gssapi && mkdir m4 && autoreconf -fi && ./configure && make && make DESTDIR=/export install
```

### PR DESCRIPTION
**Pull request by simo5**
If gssapi/gssapi_ntlmssp.h is not available simply disable NTLMSSP.

Signed-off-by: Simo Sorce <simo@redhat.com>
Closes #52

### CODE REVIEW

**Comment by devurandom** [comment]
LGTM - compiles fine here.

**Comment by simo5** [comment]
tests fail

**Comment by devurandom** [comment]
I tried running the tests, but [socket_wrapper](https://cwrap.org/socket_wrapper.html) and [nss_wrapper](https://cwrap.org/nss_wrapper.html) first appear in Debian 9 "Stretch" [[1]](https://packages.debian.org/stretch/libsocket-wrapper) [[2]](https://packages.debian.org/stretch/libnss-wrapper) and I am still at the current stable: Debian 8 "Jessie".

**Comment by simo5** [comment]
Seem like tests fails even w/o this patch.
So I am going to push it for now and then hunt down what broke them

**Pull request closed without merging**
