### PR TITLE
Do not use deprecated ap_hook_check_user_id on Apache 2.4.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by frenche** [comment]
Looks good to me.
In fact, setting AP_AUTH_INTERNAL_PER_CONF might perhaps help with cases like issue #83

**Comment by simo5** [comment]
Looks good, is the new hook a 1:1 replacement ? Or should we be worried about any side effect of this change that should go in release notes ?

**Comment by frenche** [comment]
Looks like a drop in replacement, see: https://httpd.apache.org/docs/2.4/developer/new_api_2_4.html

**Comment by simo5** [comment]
Quote: "When possible, registering all access control hooks (including authentication and authorization hooks) using AP_AUTH_INTERNAL_PER_CONF is recommended. If all modules' access control hooks are registered with this flag, then whenever the server handles an internal sub-request that matches the same set of access control configuration directives as the initial request (which is the common case), it can avoid invoking the access control hooks another time."

This actually changes something I had been trying to wor around, which is probably an improvement, but it is indeed a change. I will try to test a little before pushing, but I plan to push as is unless somethig major comes up.

**Comment by frenche** [comment]
Right, I've noticed it but I figure it shouldn't harm as the workaround just won't be called.
I guess we'll still need the workaround in the code for backward compatibility.

**Comment by simo5** [comment]
Looks like we are in agreement this is the right thing to do, pushing.

**Pull request closed without merging**
