### PR TITLE
Make sure to release the ctx when no 'mc available

### PR DESCRIPTION
**Pull request by frenche**
I don't test much with connection-bound off but this seem to make sense.

Thanks

### CODE REVIEW

**Comment by frenche** [comment]
But if (mc && !mc->ctx) we might pass NULL to gss_delete_ctx(), no?

Perhaps at cleanup:
if (ctx != GSS_C_NO_CONTEXT) gss_delete_sec_context(&min, &ctx, &output);

**Comment by simo5** [comment]
Yes we also need to check that pctx != GSS_C_NO_CONTEXT I guess

**Comment by frenche** [comment]
Well, pctx is either ctx or mc->ctx we can take care of ctx at cleanup while mc is already taken care at mag_destry_conn.

I've made some changes and added a little, please review.

Thanks,
Isaac B.

**Comment by simo5** [comment]
closed with 4160a7799f7bd642827f72c6af0fb79c660c2234

**Pull request closed without merging**
